# Generated by Django 5.2.1 on 2025-05-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0002_task_notified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='notified',
        ),
        migrations.RemoveField(
            model_name='task',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('undone', 'Не выполнено'), ('done', 'Выполнено')], default='undone', max_length=10),
        ),
    ]
